version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project:/var/www/symfony/
    expose:
      - "9001"
    ports:
      - 8000:8000
    networks:
      - symfony

networks:
  symfony:

volumes:
  project:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD
#device: ../volumes/project/
